# Configuración del servidor Quarkus
quarkus.http.port=8080

# === OptaPlanner Configuration ===
# Tiempo máximo global para buscar la solución perfecta
quarkus.optaplanner.solver.termination.spent-limit=10s

# (Opcional) Terminar antes si encuentra una puntuación aceptable
# quarkus.optaplanner.solver.termination.best-score-limit=0hard/0soft
