# Configuración del servidor Quarkus
quarkus.http.port=8080

# === Timefold Configuration ===
# Tiempo máximo global para buscar la solución perfecta
quarkus.timefold.solver.termination.spent-limit=10s

# (Opcional) Terminar antes si encuentra una puntuación aceptable
# quarkus.timefold.solver.termination.best-score-limit=0hard/0soft

# === Security Configuration (JWT) ===
# Se configura para validación usando la ruta de llaves públicas del Identity Provider.
# Usa en el futuro ${JWT_PUBLIC_KEY_LOCATION} configurado en tu Deployment Kubernetes.
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:http://aurolink-authentication:8080/q/openapi/jwks}
mp.jwt.verify.issuer=${JWT_ISSUER:https://aurolink.com}

# Permitir trafico interno sin JWT hacia el API del motor
quarkus.http.auth.permission.public.paths=/api/solver/*,/hello
quarkus.http.auth.permission.public.policy=permit
